# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: 2
  Minor: 0
  Patch: $[counter('versioncounter', 1)]
  Version: $(Major).$(Minor).$(Patch)

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/src/Akka.Persistence.PostgreSql.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/src/Akka.Persistence.PostgreSql.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/src/Akka.Persistence.PostgreSql.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Version'

- task: DotNetCoreCLI@2
  displayName: Push (to private WhereIsMyTransport Stable nuget feed)
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4ffa6051-3dec-4154-8c4f-5f21b27d2f67'